[package]
name = "quote_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.3.0"
rand = "0.8.5"
inputbot = "0.5.1"
once_cell = "1.14.0"
clipboard = "0.5.0"
crossterm = "0.25.0"
